// This file is auto-generated by scripts/gen-events.mjs from
// tasks-service/specs/tasks.asyncapi.yaml. Do NOT edit by hand — run
// `bun run generate` to refresh. Drift is enforced by test/drift.test.ts.

/**
 * Canonical snake_case envelope (grill P1.6 — do NOT camelCase).
 */
export interface TasksEventPayload {
type: ("TasksCreated" | "TasksUpdated" | "TasksDeleted")
/**
 * The resource's stable id (the event subject).
 */
actor_id: string
actor_type: string
/**
 * Bounded non-PHI label for access-control consumers.
 */
display_name: string
tenant_id: string
/**
 * ISO-8601 soft-delete timestamp, or null when live.
 */
deleted_at: string
occurred_at: string
}

export interface EventHeaders {
event_type: string
tenant_id: string
actor_id: string
actor_type: string
correlation_id: string
occurred_at: string
}
