// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { TasksHealthData, TasksHealthErrors, TasksHealthResponses, TasksProtectedProbeData, TasksProtectedProbeErrors, TasksProtectedProbeResponses, TasksProtectedWriteData, TasksProtectedWriteErrors, TasksProtectedWriteResponses, TasksReadData, TasksReadErrors, TasksReadResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Liveness probe.
 */
export const tasksHealth = <ThrowOnError extends boolean = false>(options?: Options<TasksHealthData, ThrowOnError>): RequestResult<TasksHealthResponses, TasksHealthErrors, ThrowOnError> => (options?.client ?? client).get<TasksHealthResponses, TasksHealthErrors, ThrowOnError>({ url: '/tasks/health', ...options });

/**
 * Role-gated probe (clinician, tenant-admin).
 */
export const tasksProtectedProbe = <ThrowOnError extends boolean = false>(options?: Options<TasksProtectedProbeData, ThrowOnError>): RequestResult<TasksProtectedProbeResponses, TasksProtectedProbeErrors, ThrowOnError> => (options?.client ?? client).get<TasksProtectedProbeResponses, TasksProtectedProbeErrors, ThrowOnError>({ url: '/tasks/protected', ...options });

/**
 * Demonstration write — actor bound to the JWT principal.
 */
export const tasksProtectedWrite = <ThrowOnError extends boolean = false>(options: Options<TasksProtectedWriteData, ThrowOnError>): RequestResult<TasksProtectedWriteResponses, TasksProtectedWriteErrors, ThrowOnError> => (options.client ?? client).post<TasksProtectedWriteResponses, TasksProtectedWriteErrors, ThrowOnError>({
    url: '/tasks/protected-write',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Diamond-root scoped read by id.
 */
export const tasksRead = <ThrowOnError extends boolean = false>(options: Options<TasksReadData, ThrowOnError>): RequestResult<TasksReadResponses, TasksReadErrors, ThrowOnError> => (options.client ?? client).get<TasksReadResponses, TasksReadErrors, ThrowOnError>({ url: '/tasks/{id}', ...options });
