// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://{host}/api/v1/tasks' | 'http://localhost:3000' | (string & {});
};

/**
 * Liveness probe result — any authenticated principal may call it.
 */
export type HealthStatus = {
    status: string;
    layer: string;
};

export type ProblemResponse = {
    statusCode?: number;
    status?: number;
    error?: string;
    message: string | Array<string>;
};

/**
 * Scoped single-resource read result.
 */
export type TasksRead = {
    id: string;
    status: string;
    layer: string;
    actorId: string;
};

export type TasksWriteInput = {
    /**
     * Optional free-text reason captured on the write. Trimmed runtime-side by Zod.
     */
    reason?: string;
};

/**
 * Result of the demonstration write — actorId is the JWT-derived principal, never body-supplied.
 */
export type WriteAck = {
    status: string;
    layer: string;
    actorId: string;
};

export type TasksHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tasks/health';
};

export type TasksHealthErrors = {
    /**
     * Access is unauthorized.
     */
    401: ProblemResponse;
};

export type TasksHealthError = TasksHealthErrors[keyof TasksHealthErrors];

export type TasksHealthResponses = {
    /**
     * The request has succeeded.
     */
    200: HealthStatus;
};

export type TasksHealthResponse = TasksHealthResponses[keyof TasksHealthResponses];

export type TasksProtectedProbeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tasks/protected';
};

export type TasksProtectedProbeErrors = {
    /**
     * Access is unauthorized.
     */
    401: ProblemResponse;
    /**
     * Access is forbidden.
     */
    403: ProblemResponse;
};

export type TasksProtectedProbeError = TasksProtectedProbeErrors[keyof TasksProtectedProbeErrors];

export type TasksProtectedProbeResponses = {
    /**
     * The request has succeeded.
     */
    200: HealthStatus;
};

export type TasksProtectedProbeResponse = TasksProtectedProbeResponses[keyof TasksProtectedProbeResponses];

export type TasksProtectedWriteData = {
    body: TasksWriteInput;
    headers: {
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/tasks/protected-write';
};

export type TasksProtectedWriteErrors = {
    /**
     * The server could not understand the request due to invalid syntax.
     */
    400: ProblemResponse;
    /**
     * Access is unauthorized.
     */
    401: ProblemResponse;
    /**
     * Access is forbidden.
     */
    403: ProblemResponse;
};

export type TasksProtectedWriteError = TasksProtectedWriteErrors[keyof TasksProtectedWriteErrors];

export type TasksProtectedWriteResponses = {
    /**
     * The request has succeeded.
     */
    200: WriteAck;
};

export type TasksProtectedWriteResponse = TasksProtectedWriteResponses[keyof TasksProtectedWriteResponses];

export type TasksReadData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/tasks/{id}';
};

export type TasksReadErrors = {
    /**
     * Access is unauthorized.
     */
    401: ProblemResponse;
    /**
     * Access is forbidden.
     */
    403: ProblemResponse;
    /**
     * The server cannot find the requested resource.
     */
    404: ProblemResponse;
};

export type TasksReadError = TasksReadErrors[keyof TasksReadErrors];

export type TasksReadResponses = {
    /**
     * The request has succeeded.
     */
    200: TasksRead;
};

export type TasksReadResponse = TasksReadResponses[keyof TasksReadResponses];
